//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string pttitle { get; set; }
        public string pdescription { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
