//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactioninfo
    {
        public int transactionid { get; set; }
        public string username { get; set; }
        public string pcode { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<int> TotalPrice { get; set; }
    
        public virtual product product { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
